
---
- name: installation
  hosts: all
  tasks: 
    - name: install sw application
      apt:
         name: "{{item}}"
         state: present
         update_cache: yes
      with_items:
         -git
         -maven
         -tomcat10
